### PR TITLE
Issue #140: Initial commit

### PR DESCRIPTION
**Pull request by Macarse**

### CODE REVIEW

**Comment by Macarse** [comment]
@notriddle I would like to create a feature branch and work against that. Any chance you can create a `issue140` in the bors-ng repo?

**Comment by notriddle** [comment]
You now have write access to the bors-ng repo, so you should be able to create and maintain your own branch there. However, could you please name it "bitbucket" instead of the opaque "issue140"?

**Comment by notriddle** [comment]
However, this PR is opened against your repo, not the public one. Just letting you know.

**Comment by Macarse** [comment]
@notriddle I will open the same PR against a bitbucket branch.

**Pull request closed without merging**
